version: 'build-{build}'

branches:
  only:
    - master
    - dev

  except:
    - gh-pages
    - dev-bench
    - master-bench

configuration: RELEASE

build_script: 
  - ps: .\build.ps1

# TODO: add a) running benches, b) deploying them to github repo 
